### ISSUE TITLE
Grammar Error in README.md

### ISSUE THREAD

**Issue by PatCer** [JannicHeidrich/DevOps#3]
Issue Title:
Grammar Error in Azure App Service Explanation

Repository:
DevOps

Repository Owner:
JannicHeidrich

Description:
I have identified a grammar error in the documentation related to Azure App Service in the DevOps Repository. While exploring the documentation, I noticed a grammatical inconsistency that may impact the overall clarity and understanding of the content. The error appears in a critical section where Azure App Services are explained, potentially causing confusion for users who rely on accurate and well-articulated information.

Steps to Reproduce:

Navigate to the README.md.
Locate the section explaining Azure App Service.
In the second-to-last sentence, you included a comma before the conjunction 'and'.
Expected Behavior:
The documentation should be grammatically correct and easy to comprehend.

Actual Behavior:
I observed a grammar error in the explanation, which could potentially lead to confusion.

Screenshot or Code Snippet:

![image](https://github.com/JannicHeidrich/DevOps/assets/150437961/6bf298ff-94d5-4d1e-81b2-2c82900da0ed)

Environment:

Operating System: Windows 11 Pro
Browser: Opera GX

Proposed Correction:
Remove the comma.

Note to Repository Owner:
Thank you for your work on this repository. If you need further clarification or assistance with resolving this issue, feel free to reach out.

**Comment by JannicHeidrich** [comment]
Hi PatCer, 
thanks for the hint, I have revised the grammar and will pay more attention in future repos. 

Thanks Jannic
